# _config.yml

title: "Climate Dynamics Lab"
email: "climate.lab@cas.iitd.ac.in"
description: >- # this means multi-line string
  The Climate Dynamics Lab at IIT Delhi focuses on monsoon dynamics,
  climate change, and AI applications in atmospheric sciences.

# The base URL — if your site is served from a subfolder, e.g. username.github.io/repo
baseurl: ""  # leave blank if using a user/organization site

# The URL of your GitHub Pages site
url: "https://<your-github-username>.github.io/<repo-name>"

# Build settings
theme: minima  # you can use GitHub’s default theme or your own
markdown: kramdown

# Exclude files from build if needed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

# Plugins — GitHub Pages only supports these official plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: Google Analytics or other configs can go here
