title: Climate Dynamics Lab
email: sandeep.sukumaran@cas.iitd.ac.in
description: >-
  The Climate Dynamics Lab at IIT Delhi focuses on monsoon dynamics,
  climate dynamics, monsoon studies, and AI applications in atmospheric sciences.

url: https://climdynlab.github.io
baseurl: 
back_to_top: true
# MUST be empty for user/organization sites

theme: minima  # or your custom theme if you use one
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: pretty

# Optional: Google Analytics or other configs
# google_analytics: UA-XXXXXXXX-X
