title: Climate Dynamics Lab
description: Research on Indian monsoon, climate change, and AI applications.
baseurl: "" # Keep empty for user.github.io
url: "https://climdynlab.github.io" # Replace YOURUSERNAME
